/**
 * Anfx.Pasivos.ApiService
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseDto<T = any> {
    success?: boolean;
    message?: string | null;
    errors?: string[] | null;
    statusCode?: number;
    timestamp?: string;
    data?: T;
    traceId?: string | null;
}

