/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArchivoListItemDto { 
    id?: string;
    reporteId?: number;
    nomReporte?: string | null;
    nombreArchivo?: string | null;
    contentType?: string | null;
    extension?: string | null;
    fechaCreacion?: string;
    logParameters?: string | null;
}

