/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AsignarPasivosResponce { 
    /**
     * Lista de IDs de contratos activos a asignar
     */
    listaContratos?: Array<number> | null;
    /**
     * ID de un contrato activo específico a asignar
     */
    contratosActivos?: number | null;
}

