/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovimientoItemDto } from './movimientoItemDto';


export interface CargoAdicionalViewDto { 
    idContratoPasivo?: number;
    contrato?: string | null;
    tipoCredito?: string | null;
    psV_EstatusContrato?: string | null;
    capitalFinanciado?: number | null;
    periodicidad?: string | null;
    plazo?: number | null;
    tipoMoneda?: string | null;
    fecInicioContrato?: string | null;
    fecPrimeraRenta?: string | null;
    fecActivacion?: string | null;
    fecFinContrato?: string | null;
    tasa?: string | null;
    saldoInsoluto?: number | null;
    tasaIva?: number | null;
    fechaCierre?: string | null;
    tasaEsVariable?: boolean | null;
    fondeador?: string | null;
    saldoVencido?: number;
    movimientos?: Array<MovimientoItemDto> | null;
}

