/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarteraReporteDto { 
    contrato?: string | null;
    fecVencimiento?: string | null;
    capital?: number | null;
    interes?: number | null;
    total?: number | null;
    idFondeador?: number;
    idContratoPasivo?: number;
    idContratoActivo?: number;
}

