/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SelectItemDto } from './selectItemDto';


export interface ColoniaComponentDto { 
    estado?: string | null;
    municipio?: string | null;
    codigoPostal?: string | null;
    colonias?: Array<SelectItemDto> | null;
}

