/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColoniaDto } from './coloniaDto';


export interface ColoniaDtoPagedResultDto { 
    results?: Array<ColoniaDto> | null;
    currentPage?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

