/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CuentaBancariaListItemDto } from './cuentaBancariaListItemDto';


export interface CuentaBancariaListItemDtoPagedResultDto { 
    results?: Array<CuentaBancariaListItemDto> | null;
    currentPage?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

