/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EstatusContratoListItemDto } from './estatusContratoListItemDto';


export interface EstatusContratoListItemDtoPagedResultDto { 
    results?: Array<EstatusContratoListItemDto> | null;
    currentPage?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

