/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfo } from './userInfo';


export interface LoginResponse { 
    success?: boolean;
    user?: UserInfo;
    message?: string | null;
    token?: string | null;
}

