/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetallePagoMovimientoDto } from './detallePagoMovimientoDto';


export interface MovimientoDetalleDto { 
    idMovimiento?: number;
    detalle?: Array<DetallePagoMovimientoDto> | null;
}

