/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovimientoPagoItem { 
    id?: number;
    noPago?: number;
    fecMovimiento?: string | null;
    descripcion?: string | null;
    saldoCapital?: number;
    saldoInteres?: number;
    saldoIVA?: number;
    saldoTotal?: number;
    seleccionado?: boolean;
}

