/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovimientoItemDto { 
    idMovimiento?: number;
    descripcion?: string | null;
    noPago?: number;
    fecMovimiento?: string | null;
    capital?: number;
    interes?: number;
    iva?: number;
    total?: number;
    saldoCapital?: number;
    saldoInteres?: number;
    saldoIVA?: number;
    saldoTotal?: number;
    esRenta?: boolean;
}

