/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetalleMovimientoPagoDto } from './detalleMovimientoPagoDto';


export interface PagoDetalleDto { 
    idPago?: number;
    detalle?: Array<DetalleMovimientoPagoDto> | null;
}

