/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProcesaMoratorioRequest { 
    /**
     * Fecha de procesamiento de moratorios (opcional, por defecto fecha actual)
     */
    fechaProcesamiento?: string | null;
    /**
     * ID del contrato a procesar (opcional, si no se envía procesa todos)
     */
    idContrato?: number | null;
    /**
     * Número de contrato pasivo (opcional, alternativa a IdContrato)
     */
    contratoPasivo?: string | null;
}

