/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RelActivoPasivoDto } from './relActivoPasivoDto';


export interface RelActivoPasivoDtoPagedResultDto { 
    results?: Array<RelActivoPasivoDto> | null;
    currentPage?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

