/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReporteListItemDto { 
    id?: number;
    nomReporte?: string | null;
    storedProcedure?: string | null;
    parametros?: string | null;
    activo?: boolean;
}

