/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SelectListItemDto } from './selectListItemDto';


export interface ReporteExecuteParametroDto { 
    parametroId?: string;
    inputId?: number;
    nomParametro?: string | null;
    tipoDato?: string | null;
    valueBoolean?: boolean;
    value?: string | null;
    valueDateTime?: string | null;
    tablaRef?: string | null;
    columnaValor?: string | null;
    columnaTexto?: string | null;
    display?: string | null;
    order?: number;
    dropDownList?: Array<SelectListItemDto> | null;
}

