/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TasaValorListItemDto { 
    id?: number;
    valorTasa?: number | null;
    fecValorTasa?: string | null;
    fecRegistroTasa?: string | null;
}

