/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TasaVariableListItemDto { 
    id?: number;
    nombre?: string | null;
    ultimoValor?: number | null;
    fecUltimoValor?: string | null;
}

