/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TasaVariableListItemDto } from './tasaVariableListItemDto';


export interface TasaVariableListItemDtoPagedResultDto { 
    results?: Array<TasaVariableListItemDto> | null;
    currentPage?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

