/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TasaVariableListItemDtoPagedResultDto } from './tasaVariableListItemDtoPagedResultDto';


export interface TasaVariableListItemDtoPagedResultDtoApiResponseDto { 
    success?: boolean;
    message?: string | null;
    data?: TasaVariableListItemDtoPagedResultDto;
    errors?: Array<string> | null;
    statusCode?: number;
    timestamp?: string;
    traceId?: string | null;
}

