/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TipoTablaAmortizaDto { 
    tipoTablaAmortiza: string;
    esCapitalizable?: boolean;
    activo?: boolean;
}

