/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserContextDto { 
    id?: number | null;
    username?: string | null;
    email?: string | null;
    role?: string | null;
    isAuthenticated?: boolean;
}

