/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolDto } from './rolDto';


export interface UsuarioDto { 
    id?: number;
    nombreCompleto?: string | null;
    email?: string | null;
    usuarioNombre?: string | null;
    fechaRegistro?: string;
    rolId?: number;
    activo?: boolean;
    rol?: RolDto;
}

