/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationSeverity } from './validationSeverity';


export interface ValidationError { 
    identifier?: string | null;
    errorMessage?: string | null;
    errorCode?: string | null;
    severity?: ValidationSeverity;
}
export namespace ValidationError {
}


