<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e81c90b2-af50-44bb-af4d-463e3f00b0eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.2" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anfx.Pasivos.ApiService\Anfx.Pasivos.ApiService.csproj" />
    <ProjectReference Include="..\Anfx.Pasivos.Frontend\Anfx.Pasivos.Frontend.esproj" />
  </ItemGroup>

</Project>
