/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnticipoConfigDto { 
    esLiquidacion?: boolean;
    montoAnticipo?: number;
    montoTotal?: number;
    porcIVA_Interes?: number;
    porcIVA_Pena?: number;
    calculaInteres?: boolean;
    permitePena?: boolean;
}

