/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovimientoPagoItem } from './movimientoPagoItem';


export interface CajaDto { 
    contratoPasivo?: string | null;
    fondeador?: string | null;
    idFondeador?: number | null;
    idContrato?: number | null;
    idUsuario?: number | null;
    idTipoPago: number;
    idBanco: number;
    idCuentaBancaria: number;
    fechaPago: string;
    referencia?: string | null;
    montoPago: number;
    movimientos: Array<MovimientoPagoItem>;
}

