/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CargoAdicionalDto { 
    idContrato: number;
    noPago?: number;
    descripcion: string;
    fecMovimiento: string;
    idTipoMovimiento: number;
    capital?: number;
    interes?: number;
    iva?: number;
    total: number;
    porcIVA?: number;
    generaIVA_Capital?: number;
    generaIVA_Interes?: number;
}

