/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContratoPasivoListItem { 
    contrato?: string | null;
    fondeador?: string | null;
    estatusContrato?: string | null;
    capital?: number;
    id?: number;
    fondeadorID?: number;
    idEstatusContrato?: number;
    idLineaCredito?: number;
}

