/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagoIrregularDto } from './pagoIrregularDto';


export interface ContratoPasivoEditDto { 
    fondeador?: string | null;
    idLineaCredito?: number;
    maxCapitalDisponible?: number;
    contrato?: string | null;
    lineaCredito?: string | null;
    estatusContrato?: string | null;
    tipoTasa?: boolean | null;
    idTipoCredito?: number;
    capitalFinanciado?: number;
    idPeriodicidad?: number;
    plazo?: number;
    idMoneda?: number;
    fecInicioContrato: string;
    fecPrimeraRenta?: string;
    fecActivacion?: string;
    fecFinContrato?: string;
    idTasa?: number;
    tasaBase?: number;
    puntosMas?: number;
    puntosPor?: number;
    tasa?: number;
    tasaBaseMora?: number;
    idTasaMora?: number;
    puntosMasMora?: number;
    puntosPorMora?: number;
    factorMora?: number;
    tasaMora?: number;
    tasaIva?: number;
    versionTabla?: number;
    idTipoCalculoTasaVariable?: number;
    nroRentasDepositoGarantia?: number;
    fechaFirmaContrato?: string | null;
    idTipoMantenimiento?: number;
    tasaMensual?: number;
    fechaCierre?: string | null;
    tasaEsVariable?: boolean;
    idFondeador?: number;
    factorFIRA?: number;
    idTipoTablaAmortiza?: number;
    idPeriodicidad_TTA?: number;
    idTipoCapitalizacion?: number | null;
    idTipoPagoCapital?: number | null;
    noPagosIrregulares?: number | null;
    pagos?: Array<PagoIrregularDto> | null;
}

