/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarteraDto } from './carteraDto';
import { CarteraMensualDto } from './carteraMensualDto';


export interface DashboardResponse { 
    activos?: CarteraDto;
    pasivos?: CarteraDto;
    activosMensual?: Array<CarteraMensualDto> | null;
    pasivosMensual?: Array<CarteraMensualDto> | null;
}

