/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DetallePagoMovimientoDto { 
    idPago?: number;
    tipoPago?: string | null;
    cuentaBancaria?: string | null;
    contrato?: string | null;
    fecPagoValor?: string | null;
    fecPagoRegistro?: string | null;
    montoPago?: number;
    capitalPagado?: number;
    interesPagado?: number;
    ivaPagado?: number;
    totalPagado?: number;
    estatus?: boolean;
    causaCancelacion?: string | null;
}

