/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmpresaCreateDto { 
    sEmpresa: string;
    rfc: string;
    razonSocial: string;
    telefono?: string | null;
    representante?: string | null;
    avisosEstadodeCuenta?: string | null;
    advertenciasEstadodeCuenta?: string | null;
    aclaracionesEstadodeCuenta?: string | null;
    usaDesembolso?: boolean;
    pasivo?: boolean;
    tipoDireccionId: number;
    calle?: string | null;
    numExterior?: string | null;
    numInterior?: string | null;
    coloniaId: number;
}

