/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoTablaAmortizaInfoDto } from './tipoTablaAmortizaInfoDto';


export interface TipoTablaAmortizaInfoDtoApiResponseDto { 
    success?: boolean;
    message?: string | null;
    data?: TipoTablaAmortizaInfoDto;
    errors?: Array<string> | null;
    statusCode?: number;
    timestamp?: string;
    traceId?: string | null;
}

