/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TipoCreditoDto { 
    tipoCredito: string;
    idTipoMovimiento: number;
    prefijo: string;
    sufijo: string;
    contador?: number;
    idTipoTablaAmortiza: number;
    activo?: boolean;
    idTipoMovimiento_Mora: number;
}

