/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SelectItemDto } from './selectItemDto';


export interface TipoTablaAmortizaInfoDto { 
    esCapitalizable?: boolean;
    error?: string | null;
    tipoCapitalizacion?: Array<SelectItemDto> | null;
    tipoPagoCapital?: Array<SelectItemDto> | null;
}

