/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResultStatus } from './resultStatus';
import { ValidationError } from './validationError';
import { TipoDireccionDto } from './tipoDireccionDto';


export interface TipoDireccionDtoIEnumerableResult { 
    value?: Array<TipoDireccionDto> | null;
    status?: ResultStatus;
    readonly isSuccess?: boolean;
    readonly successMessage?: string | null;
    readonly correlationId?: string | null;
    readonly location?: string | null;
    readonly errors?: Array<string> | null;
    readonly validationErrors?: Array<ValidationError> | null;
}
export namespace TipoDireccionDtoIEnumerableResult {
}


