/**
 * Anfx.Pasivos.ApiService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioCreateDto { 
    nombreCompleto: string;
    email: string;
    usuarioNombre: string;
    contrasena: string;
    rolId: number;
}

