export * from './auth.service';
import { AuthService } from './auth.service';
export * from './catalogos.service';
import { CatalogosService } from './catalogos.service';
export * from './colonias.service';
import { ColoniasService } from './colonias.service';
export * from './configuraciones.service';
import { ConfiguracionesService } from './configuraciones.service';
export * from './contratos.service';
import { ContratosService } from './contratos.service';
export * from './empresas.service';
import { EmpresasService } from './empresas.service';
export * from './reportes.service';
import { ReportesService } from './reportes.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './selectLists.service';
import { SelectListsService } from './selectLists.service';
export * from './tiposDirecciones.service';
import { TiposDireccionesService } from './tiposDirecciones.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [AuthService, CatalogosService, ColoniasService, ConfiguracionesService, ContratosService, EmpresasService, ReportesService, RolesService, SelectListsService, TiposDireccionesService, UsuariosService];
