export * from './auth.service';
import { AuthService } from './auth.service';
export * from './catalogos.service';
import { CatalogosService } from './catalogos.service';
export * from './configuraciones.service';
import { ConfiguracionesService } from './configuraciones.service';
export * from './contratos.service';
import { ContratosService } from './contratos.service';
export * from './operaciones.service';
import { OperacionesService } from './operaciones.service';
export * from './procesos.service';
import { ProcesosService } from './procesos.service';
export * from './reportes.service';
import { ReportesService } from './reportes.service';
export * from './selectLists.service';
import { SelectListsService } from './selectLists.service';
export * from './sistema.service';
import { SistemaService } from './sistema.service';
export const APIS = [AuthService, CatalogosService, ConfiguracionesService, ContratosService, OperacionesService, ProcesosService, ReportesService, SelectListsService, SistemaService];
